spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: andi1234
  jpa:
    show-sql: true
websiteUrl: http://localhost:42422